# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32043aadf1f1d9c4cf48cc84a21895038a1e51dc2e1766800f7a6ce6866ba21032505f98ff5b8e4f18654a9f073c8999a22f45ab91f02318c3b604798d8319e6

test:
  secret_key_base: af1f4bf3695bde3aca4964519ce62ecf3711ee7db5eb77b5ace4ecbea1a1c8590aa402b4cd895c28110a6788268415a895d48e00b62412823177e360b298cb19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
